[package]
name = "buildrustcrate-wasm"
version = "0.1.0"
authors = ["Malte Voos <crates@fwd.malvo.ml>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# wasm-bindgen = "0.2.71"
